name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: make build
  
      - name: Test
        run: make test

      - name: Run server
        run: |
          make run &
          server_pid=$!
          echo "Server started with PID: $server_pid"
          sleep 1m 
          echo "Stopping server..."
          kill $server_pid || true  # Send a signal to terminate the server
          wait $server_pid || true  # Wait for server to finish or error
